language: python

python:
 - "3.6"

env:
 - DOCKER_COMPOSE_VERSION=1.18.0

before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -y libdb-dev
 - docker-compose --version

install:
 - pip install -r requirements.txt

script:
 - docker-compose up -d db
 - docker ps
 - docker-compose up api
